### ISSUE TITLE
PayPal transaction fail, orchard app error log

### ISSUE THREAD

**Issue by lfurzewaddock** [OShop/OShop.PayPal#1]
### Steps to recreate

Orchard Admin Dashboard > OShop > Settings > PayPal 

Entered Client ID, Secret ID, checked 'Use sandbox' under 'Test mode', saved and clicked 'Validate Credentials' button. 

**Response: "Valid credentials."**

Used existing test account to purchase an existing test product. _See screenshot below;_

Transaction fails to complete - cannot find any log within PayPal developer site to confirm if any contact was made with the REST API. 

**Please see Orchard log below screenshot.**

![oshop-paypal-fail-1](https://cloud.githubusercontent.com/assets/5821497/8363056/77175ae6-1b74-11e5-8cce-57ec565add44.png)

2015-06-25 19:48:23,146 [13] Orchard.ContentManagement.DefaultContentManager - Default - ObjectDisposedException thrown from IContentHandler by OShop.Handlers.OrderShippingPartHandler
System.ObjectDisposedException: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at lambda_method(Closure )
   at Orchard.Data.SessionLocator.EnsureSession(IsolationLevel level) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Data\SessionLocator.cs:line 98
   at Orchard.Data.SessionLocator.Demand() in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Data\SessionLocator.cs:line 46
   at Orchard.Data.SessionLocator.For(Type entityType) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Data\SessionLocator.cs:line 40
   at Orchard.Data.Repository`1.get_Session() in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Data\Repository.cs:line 27
   at Orchard.Data.Repository`1.Get(Int32 id) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Data\Repository.cs:line 88
   at Orchard.Data.Repository`1.Orchard.Data.IRepository<T>.Get(Int32 id) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Data\Repository.cs:line 57
   at OShop.Handlers.OrderShippingPartHandler.<>c__DisplayClass9.<>c__DisplayClassb.<.ctor>b__3(OrderAddressRecord shippingAddress) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard.Web\Modules\OShop\Handlers\OrderShippingPartHandler.cs:line 29
   at Orchard.ContentManagement.Utilities.LazyField`1.GetValue() in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\Utilities\LazyField.cs:line 24
   at Orchard.ContentManagement.Utilities.LazyField`1.get_Value() in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\Utilities\LazyField.cs:line 10
   at OShop.Models.OrderShippingPart.get_ShippingAddress() in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard.Web\Modules\OShop\Models\OrderShippingPart.cs:line 22
   at OShop.Handlers.OrderShippingPartHandler.<>c__DisplayClass9.<.ctor>b__4(CreateContentContext context, OrderShippingPart part) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard.Web\Modules\OShop\Handlers\OrderShippingPartHandler.cs:line 33
   at Orchard.ContentManagement.Handlers.ContentHandler.InlineStorageFilter`1.Created(CreateContentContext context, TPart instance) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\Handlers\ContentHandler.cs:line 152
   at Orchard.ContentManagement.Handlers.StorageFilterBase`1.Orchard.ContentManagement.Handlers.IContentStorageFilter.Created(CreateContentContext context) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\Handlers\StorageFilterBase.cs:line 51
   at Orchard.ContentManagement.Handlers.ContentHandler.Orchard.ContentManagement.Handlers.IContentHandler.Created(CreateContentContext context) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\Handlers\ContentHandler.cs:line 267
   at Orchard.ContentManagement.DefaultContentManager.<>c__DisplayClass60.<Create>b__5d(IContentHandler handler) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\DefaultContentManager.cs:line 552
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\InvokeExtensions.cs:line 17

**Comment by TFleury** [comment]
Did you filled a correct currency code in OShop > Settings > General (i.e. : EUR or GBP) ?

Supported currency codes are listed [here](https://developer.paypal.com/docs/integration/direct/rest_api_payment_country_currency_support/).

**Comment by lfurzewaddock** [comment]
Ah, yes you are correct! I had entered GB, thinking the field wanted the ISO country code.

I have successfully completed a test transaction. **Thanks for your help!**

I have plenty more testing to do, but I will try to take some notes and build up a wiki to help others like me, install and configure your modules. 

Do you have any rough notes that I could use or learn from?

**Comment by TFleury** [comment]
And thank you for your tests !

OShop is not yet finalized, and I planned writing some minimal documention to use and configure it, your contributions will be welcome.
